#!/bin/bash

# Create a directory called models and navigate into it
mkdir -p models
cd models

# Download Meta-Llama-3-8B-Instruct.Q4_K_M.gguf model
huggingface-cli download QuantFactory/Meta-Llama-3-8B-Instruct-GGUF Meta-Llama-3-8B-Instruct.Q4_K_M.gguf --local-dir . --local-dir-use-symlinks False

# Download llama-2-7b.Q5_K_M.gguf model
huggingface-cli download TheBloke/Llama-2-7B-GGUF llama-2-7b.Q5_K_M.gguf --local-dir . --local-dir-use-symlinks False

curl -fsSL https://ollama.com/install.sh | sh
echo "Downloads completed successfully!"
